use_default_settings: true

server:
  bind_address: 0.0.0.0
  port: 8080
  secret_key: "CHANGE_YOURS_KEY"

search:
  default_lang: "en"
  safe_search: 0
  formats:
    - html
    - json 

ui:
  static_use_hash: true

botdetection:
  enabled: false

limiter:
  enabled: false

# engines:
#   - name: google
#     disabled: false

#   - name: bing
#     disabled: false

#   - name: duckduckgo
#     disabled: false

#   - name: startpage
#     disabled: true

#   - name: qwant
#     disabled: true

#   - name: radio_browser
#     disabled: true

#   - name: torch
#     disabled: true

#   - name: ahmia
#     disabled: true


# docker compose up -d
# In settings.yml set a strong secret: server.secret_key: "<random 32-64 chars>" (donâ€™t leave the placeholder).
# If you only need local access, change bind_address to 127.0.0.1 (optional but safer).
# Optional: set search.safe_search: 1 (moderate) if you want filtering.