use_default_settings: true

server:
  bind_address: 0.0.0.0
  port: 8080
  secret_key: "CHANGE_YOURS_KEY"

search:
  default_lang: "en"
  safe_search: 0

ui:
  static_use_hash: true


## docker compose up -d